import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { Waves, ArrowRight, BarChart3, BrainCircuit, Activity } from "lucide-react";

export default function LandingPage() {
  const handleLogin = () => {
    window.location.href = "/api/login";
  };

  return (
    <div className="min-h-screen bg-background flex flex-col">
      {/* Hero Section */}
      <div className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-primary/10 to-background z-0" />
        
        {/* Navbar */}
        <nav className="relative z-10 max-w-7xl mx-auto px-6 py-6 flex justify-between items-center">
          <div className="flex items-center gap-2">
            <Waves className="w-8 h-8 text-primary" />
            <span className="font-display font-bold text-2xl tracking-tight">SwimSync</span>
          </div>
          <Button onClick={handleLogin}>Log In / Sign Up</Button>
        </nav>

        <div className="relative z-10 max-w-7xl mx-auto px-6 py-20 md:py-32 flex flex-col items-center text-center">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 text-primary text-sm font-medium mb-6">
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-primary opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-primary"></span>
            </span>
            AI-Powered Swim Coaching
          </div>
          
          <h1 className="font-display font-bold text-5xl md:text-7xl tracking-tight mb-6 text-balance">
            Master the Water with <span className="gradient-text">Intelligent Analytics</span>
          </h1>
          
          <p className="text-lg md:text-xl text-muted-foreground max-w-2xl mb-10 text-balance">
            Track your swims, analyze your stroke efficiency, and get personalized coaching advice powered by AI. Join the next generation of swimmers.
          </p>
          
          <div className="flex flex-col sm:flex-row gap-4 w-full sm:w-auto">
            <Button size="lg" className="h-12 px-8 text-lg shadow-xl shadow-primary/20" onClick={handleLogin}>
              Get Started for Free
              <ArrowRight className="w-5 h-5 ml-2" />
            </Button>
          </div>
        </div>
      </div>

      {/* Features Grid */}
      <section className="py-20 bg-muted/30">
        <div className="max-w-7xl mx-auto px-6">
          <div className="grid md:grid-cols-3 gap-8">
            <div className="bg-card p-8 rounded-2xl shadow-sm border border-border/50 hover:shadow-md transition-all duration-300">
              <div className="w-12 h-12 bg-blue-100 dark:bg-blue-900/30 rounded-xl flex items-center justify-center text-primary mb-6">
                <Activity className="w-6 h-6" />
              </div>
              <h3 className="font-display font-bold text-xl mb-3">Activity Tracking</h3>
              <p className="text-muted-foreground">Detailed logs for pool and open water swims. Track distance, pace, strokes, and more with ease.</p>
            </div>

            <div className="bg-card p-8 rounded-2xl shadow-sm border border-border/50 hover:shadow-md transition-all duration-300">
              <div className="w-12 h-12 bg-teal-100 dark:bg-teal-900/30 rounded-xl flex items-center justify-center text-accent mb-6">
                <BrainCircuit className="w-6 h-6" />
              </div>
              <h3 className="font-display font-bold text-xl mb-3">AI Coach</h3>
              <p className="text-muted-foreground">Get personalized feedback and training plans generated by our advanced AI coaching engine.</p>
            </div>

            <div className="bg-card p-8 rounded-2xl shadow-sm border border-border/50 hover:shadow-md transition-all duration-300">
              <div className="w-12 h-12 bg-purple-100 dark:bg-purple-900/30 rounded-xl flex items-center justify-center text-purple-600 mb-6">
                <BarChart3 className="w-6 h-6" />
              </div>
              <h3 className="font-display font-bold text-xl mb-3">Advanced Analytics</h3>
              <p className="text-muted-foreground">Visualize your progress with beautiful charts. Understand your trends and break your personal records.</p>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="mt-auto py-12 px-6 border-t border-border bg-card">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-center gap-6">
          <div className="flex items-center gap-2 opacity-80">
            <Waves className="w-6 h-6" />
            <span className="font-display font-bold text-lg">SwimSync</span>
          </div>
          <p className="text-sm text-muted-foreground">
            © {new Date().getFullYear()} SwimSync. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}
